name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: fabioabreuuma
        password: 879123fefa

    - name: Pull and push
      run: |
        docker pull wordpress:latest
        docker tag wordpress:latest fabioabreuuma/wordpress:latest
        docker push fabioabreuuma/wordpress:latest
        docker pull mysql:latest
        docker tag mysql:latest fabioabreuuma/mysql:latest
        docker push fabioabreuuma/mysql:latest
